medweb_mapping:
  columns:
    date: Datum
    activity: Beschreibung der Aktivität
    employee_name: Name des Mitarbeiters
    employee_personalnummer: Personalnummer
  rules:
  - match: Baseline CT Notfall
    type: shift
    label: Baseline CT Notfall
    times:
      default: 08:00-16:00
    skill_overrides:
      notfall_ct: 1
  - match: Baseline MR Privat
    type: shift
    label: Baseline MR Privat
    times:
      default: 08:00-16:00
    skill_overrides:
      privat_mr: 1
  - match: Baseline XRAY Kinder
    type: shift
    label: Baseline XRAY Kinder
    times:
      default: 08:00-16:00
    skill_overrides:
      kinder_xray: 1
  - match: Baseline CT Gyn
    type: shift
    label: Baseline CT Gyn
    times:
      default: 08:00-16:00
    skill_overrides:
      gyn_ct: 1
balancer:
  hours_counting:
    shift_default: true
    gap_default: false
worker_roster: {}
